name: Demo One API Development

on:
  push:
    branches: [ master ]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker
      run: |
        docker build -t ghcr.io/santhoshprogrammer94/ng-pulumi-demo:$GITHUB_SHA .
      env:
        CI: true
    - ​name​: ​Login to GHCR 
​      ​uses​: ​docker/login-action@v1  
​      ​with​: 
​        ​registry​: ​ghcr.io 
​        ​username​: ​${{ secrets.GHCR_USERNAME }} 
​        ​password​: ​${{ secrets.GHCR_TOKEN }}
      run: |
        docker push ghcr.io/santhoshprogrammer94/ng-pulumi-demo:$GITHUB_SHA