name: Demo One API Development

on:
  push:
    branches: [ master ]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: santhoshprogrammer94
          password: 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

      - name: Build the Image and Push to GHCR
        run: |
          docker build . -t ghcr.io/santhoshprogrammer94/ng-pulumi-rnd:${{ github.sha }};
          docker push ghcr.io/santhoshprogrammer94/ng-pulumi-rnd:${{ github.sha }}